# Generated by Django 6.1.1 on 2026-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Шилтеме үчүн уникалдуу сөз (мисалы: adilet-diana)', unique=True)),
                ('event_type', models.CharField(choices=[('wedding', 'Үйлөнүү той'), ('kyz_uzatuu', 'Кыз узатуу'), ('beshik', 'Бешик той'), ('jubilee', 'Юбилей / Мүчөл жаш')], default='wedding', max_length=20, verbose_name='Тойдун түрү')),
                ('title_names', models.CharField(help_text='Мисалы: Адилет & Диана', max_length=100, verbose_name='Жаштардын / Үй ээсинин аты')),
                ('hosts_parents', models.CharField(help_text='Мисалы: Нүрканбек & Эльмира', max_length=150, verbose_name='Той ээлери (Ата-энеси)')),
                ('invitation_text', models.TextField(default='Сиз(дер)ди уулубуз менен келинибиздин үйлөнүү тоюна кадырлуу конок болууга чакырабыз.', verbose_name='Чакыруу тексти')),
                ('event_date', models.DateField(verbose_name='Тойдун датасы')),
                ('event_time', models.TimeField(default='17:00', verbose_name='Башталуу убактысы')),
                ('city', models.CharField(default='Базар-Коргон шаары', max_length=100, verbose_name='Шаар / Айыл')),
                ('restaurant_name', models.CharField(default='«Долоно» рестораны', max_length=100, verbose_name='Ресторандын аты')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='2GIS / Яндекс Карта шилтемеси')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Башкы сүрөт')),
                ('bg_music', models.FileField(blank=True, null=True, upload_to='music/', verbose_name='Музыка (MP3)')),
                ('phone_number', models.CharField(help_text='Мисалы: 996700000000', max_length=20, verbose_name='WhatsApp номер (RSVP үчүн)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
