# Generated by Django 6.1.1 on 2026-09-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='bg_music',
            new_name='music',
        ),
    ]
