# Generated by Django 6.1.1 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_rename_bg_music_invitation_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='bride_name',
            field=models.CharField(default='Айдай', help_text='Мисалы: Айдай', max_length=50, verbose_name='Келиндин аты'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_name',
            field=models.CharField(default='Байыш', help_text='Мисалы: Байыш', max_length=50, verbose_name='Күйөө баланын аты'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(help_text='Шилтеме үчүн уникалдуу сөз', unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='title_names',
            field=models.CharField(blank=True, help_text='Мисалы: Байыш & Айдай', max_length=100, verbose_name='Жаштардын / Үй ээсинин аты'),
        ),
    ]
