# Generated by Django 6.1.1 on 2026-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_bride_name_invitation_groom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_text',
            field=models.TextField(blank=True, help_text='Жөнтек той, уул той, үй той ж.б. жараша толук текстти жазыңыз.', null=True, verbose_name='Чакыруу тексти'),
        ),
    ]
