# Generated by Django 6.1.1 on 2026-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_invitation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='title_names',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='bride_name',
            field=models.CharField(blank=True, help_text='Мисалы: Айдай', max_length=50, null=True, verbose_name='Келиндин аты'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='city',
            field=models.CharField(default='Бишкек шаары', max_length=100, verbose_name='Шаар / Айыл'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='groom_name',
            field=models.CharField(blank=True, help_text='Мисалы: Байыш', max_length=50, null=True, verbose_name='Күйөө баланын аты'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='restaurant_name',
            field=models.CharField(max_length=100, verbose_name='Ресторандын аты'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.SlugField(help_text='Шилтеме үчүн уникалдуу сөз', unique=True, verbose_name='Шилтеме (slug)'),
        ),
    ]
