# Generated by Django 6.1.1 on 2026-09-08 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_remove_invitation_title_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_text',
            field=models.TextField(blank=True, null=True, verbose_name='Чакыруу тексти'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Мисалы: Асан & Үсөн', max_length=100, verbose_name='Коноктун аты')),
                ('token', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_attending', models.BooleanField(blank=True, null=True, verbose_name='Келеби?')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
        ),
    ]
