# Generated by Django 6.1.1 on 2026-09-17 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_alter_invitation_invitation_text_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Башкы сүрөт'),
        ),
    ]
