# Generated by Django 5.1.6 on 2026-09-18 15:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitation_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='covers/', verbose_name='Башкы сүрөт'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='music',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='music/', verbose_name='Музыка (MP3)'),
        ),
    ]
